version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.3.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: nvm install yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run: npx chromatic --project-token=nlffc37hgg --exit-zero-on-changes